<a href="https://colab.research.google.com/github/sominshim/DL_beginner/blob/main/%EC%8B%A4%EC%8A%B52.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DL_1_2_linear_regression.py

In [ ]:
import tensorflow as tf

# 공부한 시간
x = [[1],
     [2],
     [3]]
# 성적
y = [[1],
     [2],
     [3]]

model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(1))

model.compile(optimizer=tf.keras.optimizers.SGD(0.1),
              loss=tf.keras.losses.mse)

model.fit(x, y, epochs=10)

# 퀴즈
# x가 5와 7일 때의 결과는 얼마입니까?
print(model.predict(x))
print(model.predict([[1],
                     [2],
                     [3]]))
print(model.predict([[5],
                     [7]]))

Epoch 1/10
1/1 [==============================] - 3s 3s/step - loss: 28.8449
Epoch 2/10
1/1 [==============================] - 0s 7ms/step - loss: 0.4579
Epoch 3/10
1/1 [==============================] - 0s 8ms/step - loss: 0.1134
Epoch 4/10
1/1 [==============================] - 0s 9ms/step - loss: 0.1041
Epoch 5/10
1/1 [==============================] - 0s 8ms/step - loss: 0.0992
Epoch 6/10
1/1 [==============================] - 0s 8ms/step - loss: 0.0944
Epoch 7/10
1/1 [==============================] - 0s 10ms/step - loss: 0.0900
Epoch 8/10
1/1 [==============================] - 0s 9ms/step - loss: 0.0857
Epoch 9/10
1/1 [==============================] - 0s 8ms/step - loss: 0.0816
Epoch 10/10
1/1 [==============================] - 0s 67ms/step
[[1.4023898]
 [2.0863523]
 [2.7703152]]
1/1 [==============================] - 0s 34ms/step
[[1.4023898]
 [2.0863523]
 [2.7703152]]
1/1 [==============================] - 0s 28ms/step
[[4.1382403]
 [5.5061655]]


# DL_1_3_multiple_regression.py

In [ ]:
# DL_1_3_multiple_regression.py
import tensorflow as tf

# 공부시간, 출석일수
x = [[1, 2],
     [2, 1],
     [4, 5],
     [5, 4],
     [8, 9],
     [9, 8]]
y = [[3],
     [3],
     [9],
     [9],
     [17],
     [17]]

model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(shape=[2]))
model.add(tf.keras.layers.Dense(1))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 3         
                                                                 
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer=tf.keras.optimizers.SGD(0.01),
              loss=tf.keras.losses.mse)

model.fit(x, y, epochs=100, verbose=2)

# 퀴즈
# 5시간 공부하고 2번 출석한 학생과
# 3시간 공부하고 6번 출석한 학생의 성적을 구하세요
print(model.predict([[5, 2],
                             [3, 6]], verbose=0))

SyntaxError: ignored

# DL_2_1_trees.py

In [ ]:
import pandas as pd

df = pd.read_csv('/content/gdrive/MyDrive/디지털오픈랩 딥러닝 교육/data/trees.csv')
df.head()

Unnamed: 0  Girth  Height  Volume
0           1    8.3      70    10.3
1           2    8.6      65    10.3
2           3    8.8      63    10.2
3           4   10.5      72    16.4
4           5   10.7      81    18.8

In [ ]:
# 데이터 잘 불러오는 방법
df = pd.read_csv('/content/gdrive/MyDrive/디지털오픈랩 딥러닝 교육/data/trees.csv',
                            index_col=0)
df.head()

Girth  Height  Volume
1    8.3      70    10.3
2    8.6      65    10.3
3    8.8      63    10.2
4   10.5      72    16.4
5   10.7      81    18.8

In [ ]:
# 데이터 잘 불러오는 방법
df = pd.read_csv('/content/gdrive/MyDrive/디지털오픈랩 딥러닝 교육/data/trees.csv',
                            index_col=0)
df.head()

Girth  Height  Volume
1    8.3      70    10.3
2    8.6      65    10.3
3    8.8      63    10.2
4   10.5      72    16.4
5   10.7      81    18.8

In [ ]:
print(df, end='\n\n')
print(df.values, end='\n\n')

    Girth  Height  Volume
1     8.3      70    10.3
2     8.6      65    10.3
3     8.8      63    10.2
4    10.5      72    16.4
5    10.7      81    18.8
6    10.8      83    19.7
7    11.0      66    15.6
8    11.0      75    18.2
9    11.1      80    22.6
10   11.2      75    19.9
11   11.3      79    24.2
12   11.4      76    21.0
13   11.4      76    21.4
14   11.7      69    21.3
15   12.0      75    19.1
16   12.9      74    22.2
17   12.9      85    33.8
18   13.3      86    27.4
19   13.7      71    25.7
20   13.8      64    24.9
21   14.0      78    34.5
22   14.2      80    31.7
23   14.5      74    36.3
24   16.0      72    38.3
25   16.3      77    42.6
26   17.3      81    55.4
27   17.5      82    55.7
28   17.9      80    58.3
29   18.0      80    51.5
30   18.0      80    51.0
31   20.6      87    77.0

[[ 8.3 70.  10.3]
 [ 8.6 65.  10.3]
 [ 8.8 63.  10.2]
 [10.5 72.  16.4]
 [10.7 81.  18.8]
 [10.8 83.  19.7]
 [11.  66.  15.6]
 [11.  75.  18.2]
 [11.1 80.  22.6]
 [11.

In [ ]:
x = df.values[:, :-1]
# y = df.values[:, -1] # 1차원
y = df.values[:, -1:]   # 2차원
print(x.shape, y.shape)

(31, 2) (31, 1)


In [ ]:
# quize
# trees.csv 파일을 읽고 학습하는 모델을 구축해서
# Birth 가 15이고 Height = 70 인 나무와, 
# Birth 가 20이고 Height = 80 인 나무의 Volume을 구하세요

In [ ]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(shape=[2]))
model.add(tf.keras.layers.Dense(1))
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_5 (Dense)             (None, 1)                 3         
                                                                 
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer=tf.keras.optimizers.SGD(0.00007),
              loss=tf.keras.losses.mse)

model.fit(x, y, epochs=1000, verbose=1)

Epoch 1/1000
1/1 [==============================] - 0s 331ms/step - loss: 59.1957
Epoch 2/1000
1/1 [==============================] - 0s 8ms/step - loss: 59.1492
Epoch 3/1000
1/1 [==============================] - 0s 6ms/step - loss: 59.1028
Epoch 4/1000
1/1 [==============================] - 0s 8ms/step - loss: 59.0565
Epoch 5/1000
1/1 [==============================] - 0s 8ms/step - loss: 59.0102
Epoch 6/1000
1/1 [==============================] - 0s 10ms/step - loss: 58.9641
Epoch 7/1000
1/1 [==============================] - 0s 9ms/step - loss: 58.9180
Epoch 8/1000
1/1 [==============================] - 0s 9ms/step - loss: 58.8721
Epoch 9/1000
1/1 [==============================] - 0s 12ms/step - loss: 58.8262
Epoch 10/1000
1/1 [==============================] - 0s 7ms/step - loss: 58.7804
Epoch 11/1000
1/1 [==============================] - 0s 8ms/step - loss: 58.7347
Epoch 12/1000
1/1 [==============================] - 0s 6ms/step - loss: 58.6891
Epoch 13/1000
1/1 [==============

In [ ]:
print(model.predict([[15, 70],
                                 [20, 80]], verbose=0))

[[40.377457]
 [58.627125]]


# DL_2_2_logistic_regression

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

print(np.e)

2.718281828459045


In [ ]:
def show_sigmoid():
    # z = wx + b
    def sigmoid(z):
        return 1 / (1 + np.e ** -z)

    for z in np.linspace(-10, 10, 100):
        s = sigmoid(z)
        plt.plot(z, s, 'ro')
    
    plt.show()

In [ ]:
def logistic_regression():

    # 공부시간, 출석일수
    x = [[1, 2],  # 탈락
        [2, 1],
        [4, 5],     # 통과
        [5, 4],
        [8, 9],
        [9, 8]]
    y = [[0],
        [0],
        [1],
        [1],
        [1],
        [1]]

    model = tf.keras.Sequential()
    model.add(tf.keras.layers.Input(shape=[2]))
    model.add(tf.keras.layers.Dense(1, activation='sigmoid'))
    model.summary()    

    model.compile(optimizer=tf.keras.optimizers.SGD(0.01),
                loss=tf.keras.losses.binary_crossentropy,
                metrics='acc')

    model.fit(x, y, epochs=100, verbose=2)
    
    return model

In [ ]:
model = logistic_regression()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 1)                 3         
                                                                 
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
1/1 - 0s - loss: 2.0960 - acc: 0.3333 - 339ms/epoch - 339ms/step
Epoch 2/100
1/1 - 0s - loss: 1.7921 - acc: 0.3333 - 9ms/epoch - 9ms/step
Epoch 3/100
1/1 - 0s - loss: 1.5118 - acc: 0.3333 - 9ms/epoch - 9ms/step
Epoch 4/100
1/1 - 0s - loss: 1.2633 - acc: 0.3333 - 8ms/epoch - 8ms/step
Epoch 5/100
1/1 - 0s - loss: 1.0544 - acc: 0.3333 - 9ms/epoch - 9ms/step
Epoch 6/100
1/1 - 0s - loss: 0.8893 - acc: 0.3333 - 8ms/epoch - 8ms/step
Epoch 7/100
1/1 - 0s - loss: 0.7663 - acc: 0.3333 - 10ms/epoch - 10ms/step
Epoch 8/100
1/1 - 0s - loss: 0.6780 - acc: 0.6667 - 9ms/epoch - 9ms/ste

In [ ]:
# 공부시간, 출석일수
x = [[1, 2],  # 탈락
    [2, 1],
    [4, 5],     # 통과
    [5, 4],
    [8, 9],
    [9, 8]]
y = [[0],
    [0],
    [1],
    [1],
    [1],
    [1]]
print(model.evaluate(x, y, verbose=0)) # loss, accuarcy 출력

[0.3958665132522583, 0.6666666865348816]


In [ ]:
# quize
# 5시간 공부하고 2번 출석한 학생과
# 3시간 공부하고 6번 출석한 학생의 성적을 구하세요
p = model.predict(x, verbose=0)
print(p)
print(model.predict([[5, 2],
                                [3, 6]], verbose=2))

[[0.61954546]
 [0.6310551 ]
 [0.84162545]
 [0.84806424]
 [0.9625787 ]
 [0.9643087 ]]
1/1 - 0s - 28ms/epoch - 28ms/step
[[0.7980859 ]
 [0.83496684]]


In [ ]:
p_bool = np.int32(p > 0.5)
p_bool

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1]], dtype=int32)

In [ ]:
equals = (p_bool == y)
print(equals)

[[False]
 [False]
 [ True]
 [ True]
 [ True]
 [ True]]


In [ ]:
print('acc :', np.mean(equals))

acc : 0.6666666666666666


# DL_2_3_pima.py

### Quiz
피마 인디언 당뇨변 데이터에 대한 모델을 구축하세요.

In [ ]:
import pandas as pd
from sklearn import preprocessing, model_selection
import numpy as np

In [ ]:
df = pd.read_csv("/content/gdrive/MyDrive/디지털오픈랩 딥러닝 교육/data/pima-indians-diabetes.csv")

상단에 주석과 같은 필요없는 글이 있을 때,
pd.read_csv() 파라미터 skiprows 를 통해 무시할 행의 갯수를 표기한다.
또한 header=None 를 통해 첫번째 행을 칼럼명으로 가져오는 것을 방지한다.

In [ ]:
df = pd.read_csv("/content/gdrive/MyDrive/디지털오픈랩 딥러닝 교육/data/pima-indians-diabetes.csv", 
                #  skiprows = 9, # -> 삭제했기 때문에 주석처리
                 header = None)

In [ ]:
df = pd.read_csv("/content/gdrive/MyDrive/디지털오픈랩 딥러닝 교육/data/pima-indians-diabetes.csv")

In [ ]:
df.head()

6  148  72  35    0  33.6  0.627  50  1
0  1   85  66  29    0  26.6  0.351  31  0
1  8  183  64   0    0  23.3  0.672  32  1
2  1   89  66  23   94  28.1  0.167  21  0
3  0  137  40  35  168  43.1  2.288  33  1
4  5  116  74   0    0  25.6  0.201  30  0

In [ ]:
columns_name = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome']

In [ ]:
df = pd.read_csv("/content/gdrive/MyDrive/디지털오픈랩 딥러닝 교육/data/pima-indians-diabetes.csv", names = columns_name)

In [ ]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
def logistic_regression(x, y):

    model = tf.keras.Sequential()
    model.add(tf.keras.layers.Input(shape=[8]))
    model.add(tf.keras.layers.Dense(1, activation='sigmoid'))
    model.summary()    

    model.compile(optimizer=tf.keras.optimizers.SGD(0.001),
                loss=tf.keras.losses.binary_crossentropy,
                metrics='acc')

    model.fit(x, y, epochs=200, verbose=2)
    
    return model

In [ ]:
x = df.values[:, :-1]
# y = df.values[:, -1] # 1차원
y = df.values[:, -1:]   # 2차원
print(x.shape, y.shape)

(768, 8) (768, 1)


## train test split

In [ ]:
# 주먹구구 식
train_size = int(len(x) * 0.7)
x_train, x_test = x[:train_size], x[train_size:]
y_train, y_test = y[:train_size], y[train_size:]

In [ ]:
data = model_selection.train_test_split(x, y, train_size=0.75, shuffle=True) 
# (Tip) command 함수 클릭 -> 함수의 파라미터 도움말를 볼 수 있음
x_train, x_test, y_train, y_test = data

In [ ]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(576, 8) (576, 1)
(192, 8) (192, 1)


In [ ]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(537, 8) (537, 1)
(231, 8) (231, 1)


## 학습데이터 스케일링 
- normalization
- minmax
- standardization

In [ ]:
# x = preprocessing.scale(x)
# x = preprocessing.minmax_scale(x)

In [ ]:
scaler = preprocessing.StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
model = logistic_regression(x_train, y_train)

Model: "sequential_16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_16 (Dense)            (None, 1)                 9         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________
Epoch 1/200
18/18 - 0s - loss: 0.7073 - acc: 0.5660 - 311ms/epoch - 17ms/step
Epoch 2/200
18/18 - 0s - loss: 0.7050 - acc: 0.5694 - 35ms/epoch - 2ms/step
Epoch 3/200
18/18 - 0s - loss: 0.7026 - acc: 0.5712 - 37ms/epoch - 2ms/step
Epoch 4/200
18/18 - 0s - loss: 0.7003 - acc: 0.5729 - 35ms/epoch - 2ms/step
Epoch 5/200
18/18 - 0s - loss: 0.6981 - acc: 0.5747 - 35ms/epoch - 2ms/step
Epoch 6/200
18/18 - 0s - loss: 0.6958 - acc: 0.5747 - 37ms/epoch - 2ms/step
Epoch 7/200
18/18 - 0s - loss: 0.6936 - acc: 0.5764 - 35ms/epoch - 2ms/step
Epoch 8/200
18/18 - 0s - loss: 0.6914 - acc: 0.5799 -

In [ ]:
model.evaluate(x_test, y_test)

6/6 [==============================] - 0s 3ms/step - loss: 0.5622 - acc: 0.7240


[0.5622296929359436, 0.7239583134651184]

In [ ]:
p = model.predict(x_test, verbose=0)

In [ ]:
p_test = (p > 0.5)
print('acc:', np.mean(p_test == y_test))

acc: 0.7239583333333334


In [ ]:
np.int32([1,2,3]) + 1
a = np.arange(10)
a + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# numpy

In [ ]:
import numpy as np

a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [ ]:
print(a+1)  # broadcast

[1 2 3 4 5 6]


In [ ]:
print(a+a)  # vector

[ 0  2  4  6  8 10]


In [ ]:
print(np.sin(a))    # universal function

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [ ]:
np.sin([0,1,2,3])

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [ ]:
a = [1, 2, 3]

In [ ]:
a+ a

[1, 2, 3, 1, 2, 3]

# DL_3_1_softmax_regression.py

In [ ]:
#   y         x.          w
# (7, 2)  = (3, 5) * (5, 2) > weight 개수와 feature 개수가 같아야 한다. 
# (7, 1)  = (7, 2) * (2, 1)

red, green, blue = 0, 1, 2 로 매핑하면 안된다.

왜냐하면 logistic regression 은 0, 1로만 구분하기 때문이다.

따라서 
- red = 1, 0, 0
- green = 0, 1, 0
- blue = 0, 0, 1

로 변환해야 함, = one-hot encoding

In [ ]:
x = [[1, 2],  # C
        [2, 1],
        [4, 5],     # B
        [5, 4],
        [8, 9],     # A
        [9, 8]]
y = [[0, 0, 1],
    [0, 0, 1],
    [0, 1, 0],
    [0, 1, 0],
    [1, 0, 0],
    [1, 0, 0]]

In [ ]:
def softmax_regression_onehot(x, y):
    model = tf.keras.Sequential()

    model.add(tf.keras.layers.Input(shape=[2]))
    # (6, 3) = (6, 2) @ (2, 3)  
    # -> weight 변수 갯수는 6개인데, 왜 model parameter 갯수는 9개? -> bias 3개가 추가되기 때문
    model.add(tf.keras.layers.Dense(3, activation='softmax'))
    model.summary()    

    model.compile(optimizer=tf.keras.optimizers.SGD(0.01),
                loss=tf.keras.losses.categorical_crossentropy,
                metrics='acc')

    model.fit(x, y, epochs=300, verbose=2)

    return model

In [ ]:
model = softmax_regression_onehot(x, y)

Model: "sequential_18"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_18 (Dense)            (None, 3)                 9         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________
Epoch 1/300
1/1 - 0s - loss: 5.8010 - acc: 0.3333 - 478ms/epoch - 478ms/step
Epoch 2/300
1/1 - 0s - loss: 5.2708 - acc: 0.3333 - 15ms/epoch - 15ms/step
Epoch 3/300
1/1 - 0s - loss: 4.7625 - acc: 0.3333 - 8ms/epoch - 8ms/step
Epoch 4/300
1/1 - 0s - loss: 4.2900 - acc: 0.3333 - 8ms/epoch - 8ms/step
Epoch 5/300
1/1 - 0s - loss: 3.8766 - acc: 0.1667 - 8ms/epoch - 8ms/step
Epoch 6/300
1/1 - 0s - loss: 3.5506 - acc: 0.1667 - 7ms/epoch - 7ms/step
Epoch 7/300
1/1 - 0s - loss: 3.3235 - acc: 0.1667 - 7ms/epoch - 7ms/step
Epoch 8/300
1/1 - 0s - loss: 3.1727 - acc: 0.3333 - 7ms/epoch - 7ms/st

In [ ]:
p = model.predict(x, verbose=0)
print(p)

[[0.24458332 0.3409932  0.4144235 ]
 [0.2975201  0.4264332  0.2760467 ]
 [0.44949892 0.35469976 0.19580129]
 [0.48786107 0.39577138 0.11636752]
 [0.69413066 0.25644353 0.04942586]
 [0.70482063 0.26769787 0.02748148]]


In [ ]:
p_arg = np.argmax(p, axis=1)
p_arg

array([2, 1, 0, 0, 0, 0])

In [ ]:
y_arg = np.argmax(y, axis=1)
y_arg

array([2, 2, 1, 1, 0, 0])

In [ ]:
acc = np.mean(p_arg == y_arg)
print('acc: ', acc)

acc:  0.5


## 실제 사용코드

In [ ]:
#   y         x.          w
# (3, 2)  = (3, 5) * (5, 2) > weight 개수와 feature 개수가 같아야 한다. 
# (7, 1)  = (7, 2) * (2, 1)

red, green, blue = 0, 1, 2 로 매핑하면 안된다.

왜냐하면 logistic regression 은 0, 1로만 구분하기 때문이다.

따라서 
- red = 1, 0, 0
- green = 0, 1, 0
- blue = 0, 0, 1

로 변환해야 함, = one-hot encoding

In [ ]:
def softmax_regression_sparse(x, y):
    model = tf.keras.Sequential()

    model.add(tf.keras.layers.Input(shape=[2]))
    # (6, 3) = (6, 2) @ (2, 3)  
    # -> weight 변수 갯수는 6개인데, 왜 model parameter 갯수는 9개? -> bias 3개가 추가되기 때문
    model.add(tf.keras.layers.Dense(3, activation='softmax'))
    model.summary()    

    model.compile(optimizer=tf.keras.optimizers.SGD(0.01),
                loss=tf.keras.losses.sparse_categorical_crossentropy,
                metrics='acc')

    model.fit(x, y, epochs=300, verbose=2)

    return model

In [ ]:
x = [[1, 2],  # C
        [2, 1],
        [4, 5],     # B
        [5, 4],
        [8, 9],     # A
        [9, 8]]
y = [2,
     2,
     1,
     1,
     0,
     0]

In [ ]:
model = softmax_regression_sparse(x, y)

Model: "sequential_24"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_24 (Dense)            (None, 3)                 9         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________
Epoch 1/300
1/1 - 0s - loss: 6.2898 - acc: 0.3333 - 241ms/epoch - 241ms/step
Epoch 2/300
1/1 - 0s - loss: 5.7412 - acc: 0.3333 - 9ms/epoch - 9ms/step
Epoch 3/300
1/1 - 0s - loss: 5.2014 - acc: 0.3333 - 9ms/epoch - 9ms/step
Epoch 4/300
1/1 - 0s - loss: 4.6732 - acc: 0.3333 - 8ms/epoch - 8ms/step
Epoch 5/300
1/1 - 0s - loss: 4.1611 - acc: 0.3333 - 7ms/epoch - 7ms/step
Epoch 6/300
1/1 - 0s - loss: 3.6722 - acc: 0.3333 - 8ms/epoch - 8ms/step
Epoch 7/300
1/1 - 0s - loss: 3.2165 - acc: 0.3333 - 8ms/epoch - 8ms/step
Epoch 8/300
1/1 - 0s - loss: 2.8069 - acc: 0.1667 - 15ms/epoch - 15ms/st

In [ ]:
p = model.predict(x, verbose=0)
print(p)

[[0.2268167  0.4383908  0.33479244]
 [0.3553608  0.28212598 0.3625132 ]
 [0.3909516  0.4546661  0.15438233]
 [0.5712271  0.27287617 0.15589681]
 [0.602832   0.35613146 0.04103645]
 [0.7753692  0.1881523  0.0364784 ]]


In [ ]:
p_arg = np.argmax(p, axis=1)
p_arg

array([1, 2, 1, 0, 0, 0])

In [ ]:
y

[2, 2, 1, 1, 0, 0]

In [ ]:
acc = np.mean(p_arg == y)
print('acc: ', acc)

acc:  0.6666666666666666


# DL_4_1_iris.py

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing, model_selection
import tensorflow as tf

In [ ]:
df = pd.read_csv("/content/gdrive/MyDrive/디지털오픈랩 딥러닝 교육/data/iris.csv")

In [ ]:
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
df['variety'].unique()

array(['Setosa', 'Versicolor', 'Virginica'], dtype=object)

In [ ]:
x = df.values[:, :-1]
x = np.float32(x)
y = df.values[:, -1]

In [ ]:
encoder = preprocessing.LabelBinarizer()
y = encoder.fit_transform(y)

In [ ]:
print('x: ', x.dtype,
        '\ny: ',  y.dtype)

x:  float32 
y:  int64


## Quiz 
앞에서 읽어온 데이터에 대해 80%로 학습하고

 28%에 대해 정확도를 구하세요

In [ ]:
print(x.shape, y.shape)

(150, 4) (150, 3)


In [ ]:
x_train, x_test, y_train, y_test = model_selection.train_test_split(x, y, train_size=0.75, shuffle=True) 

In [ ]:
def softmax_regression_onehot(x, y):
    model = tf.keras.Sequential()

    model.add(tf.keras.layers.Input(shape=[4]))
    model.add(tf.keras.layers.Dense(3, activation='softmax'))
    model.summary()    

    model.compile(optimizer=tf.keras.optimizers.SGD(0.01),
                loss=tf.keras.losses.categorical_crossentropy,
                metrics='acc')

    model.fit(x, y, epochs=300, verbose=2)

    return model

In [ ]:
model = softmax_regression_onehot(x_train, y_train)

In [ ]:
model.evaluate(x_test, y_test)

2/2 [==============================] - 0s 9ms/step - loss: 0.3053 - acc: 0.9474


[0.3052500784397125, 0.9473684430122375]

In [ ]:
p = model.predict(x_test)
p_arg = np.argmax(p, axis=1)
y_arg = np.argmax(y_test, axis=1)

2/2 [==============================] - 0s 5ms/step


In [ ]:
arr = np.mean(p_arg == y_arg)

In [ ]:
arr

0.9473684210526315

# DL_4_1_iris_sparse.py

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing, model_selection
import tensorflow as tf

In [ ]:
df = pd.read_csv("/content/gdrive/MyDrive/디지털오픈랩 딥러닝 교육/data/iris.csv")

In [ ]:
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
df['variety'].unique()

array(['Setosa', 'Versicolor', 'Virginica'], dtype=object)

In [ ]:
x = df.values[:, :-1]
x = np.float32(x)
y = df.values[:, -1]

In [ ]:
encoder = preprocessing.LabelEncoder()
y = encoder.fit_transform(y)

In [ ]:
print('x: ', x.dtype,
        '\ny: ',  y.dtype)

x:  float32 
y:  int64


## Quiz 
앞에서 읽어온 데이터에 대해 80%로 학습하고

 28%에 대해 정확도를 구하세요

In [ ]:
print(x.shape, y.shape)

(150, 4) (150,)


In [ ]:
x_train, x_test, y_train, y_test = model_selection.train_test_split(x, y, train_size=0.75, shuffle=True) 

In [ ]:
def softmax_regression_onehot(x, y):
    model = tf.keras.Sequential()

    model.add(tf.keras.layers.Input(shape=[4]))
    model.add(tf.keras.layers.Dense(3, activation='softmax'))
    model.summary()    

    model.compile(optimizer=tf.keras.optimizers.SGD(0.01),
                loss=tf.keras.losses.sparse_categorical_crossentropy,
                metrics='acc')

    model.fit(x, y, epochs=300, verbose=2)

    return model

In [ ]:
model = softmax_regression_onehot(x_train, y_train)

In [ ]:
model.evaluate(x_test, y_test)

2/2 [==============================] - 0s 9ms/step - loss: 0.2789 - acc: 1.0000


[0.27888208627700806, 1.0]

In [ ]:
p = model.predict(x_test)
p_arg = np.argmax(p, axis=1)
# y_arg = np.argmax(y_test, axis=1)

2/2 [==============================] - 0s 5ms/step


In [ ]:
arr = np.mean(p_arg == y_test)
arr

1.0