# DL_1_2_linear_regression.py

In [1]:
import tensorflow as tf

# 공부한 시간
x = [[1],
     [2],
     [3]]
# 성적
y = [[1],
     [2],
     [3]]

model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(1))

model.compile(optimizer=tf.keras.optimizers.SGD(0.1),
              loss=tf.keras.losses.mse)

model.fit(x, y, epochs=10)

# 퀴즈
# x가 5와 7일 때의 결과는 얼마입니까?
print(model.predict(x))
print(model.predict([[1],
                     [2],
                     [3]]))
print(model.predict([[5],
                     [7]]))

Epoch 1/10
1/1 [==============================] - 3s 3s/step - loss: 1.1324
Epoch 2/10
1/1 [==============================] - 0s 18ms/step - loss: 0.0180
Epoch 3/10
1/1 [==============================] - 0s 23ms/step - loss: 0.0045
Epoch 4/10
1/1 [==============================] - 0s 11ms/step - loss: 0.0041
Epoch 5/10
1/1 [==============================] - 0s 17ms/step - loss: 0.0039
Epoch 6/10
1/1 [==============================] - 0s 22ms/step - loss: 0.0037
Epoch 7/10
1/1 [==============================] - 0s 10ms/step - loss: 0.0035
Epoch 8/10
1/1 [==============================] - 0s 18ms/step - loss: 0.0034
Epoch 9/10
1/1 [==============================] - 0s 10ms/step - loss: 0.0032
Epoch 10/10
1/1 [==============================] - 0s 118ms/step
[[0.9202701]
 [1.98289  ]
 [3.04551  ]]
1/1 [==============================] - 0s 50ms/step
[[0.9202701]
 [1.98289  ]
 [3.04551  ]]
1/1 [==============================] - 0s 33ms/step
[[5.17075  ]
 [7.2959895]]


# DL_1_3_multiple_regression.py

In [2]:
# DL_1_3_multiple_regression.py
import tensorflow as tf

# 공부시간, 출석일수
x = [[1, 2],
     [2, 1],
     [4, 5],
     [5, 4],
     [8, 9],
     [9, 8]]
y = [[3],
     [3],
     [9],
     [9],
     [17],
     [17]]

model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(shape=[2]))
model.add(tf.keras.layers.Dense(1))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [3]:
model.compile(optimizer=tf.keras.optimizers.SGD(0.01),
              loss=tf.keras.losses.mse)

model.fit(x, y, epochs=100, verbose=2)

# 퀴즈
# 5시간 공부하고 2번 출석한 학생과
# 3시간 공부하고 6번 출석한 학생의 성적을 구하세요
print(model.predict([[5, 2], [3, 6]], verbose=0))

Epoch 1/100
1/1 - 0s - loss: 0.0086 - 462ms/epoch - 462ms/step
Epoch 2/100
1/1 - 0s - loss: 0.0082 - 11ms/epoch - 11ms/step
Epoch 3/100
1/1 - 0s - loss: 0.0080 - 8ms/epoch - 8ms/step
Epoch 4/100
1/1 - 0s - loss: 0.0079 - 13ms/epoch - 13ms/step
Epoch 5/100
1/1 - 0s - loss: 0.0077 - 18ms/epoch - 18ms/step
Epoch 6/100
1/1 - 0s - loss: 0.0076 - 13ms/epoch - 13ms/step
Epoch 7/100
1/1 - 0s - loss: 0.0074 - 7ms/epoch - 7ms/step
Epoch 8/100
1/1 - 0s - loss: 0.0073 - 25ms/epoch - 25ms/step
Epoch 9/100
1/1 - 0s - loss: 0.0071 - 9ms/epoch - 9ms/step
Epoch 10/100
1/1 - 0s - loss: 0.0070 - 9ms/epoch - 9ms/step
Epoch 11/100
1/1 - 0s - loss: 0.0069 - 6ms/epoch - 6ms/step
Epoch 12/100
1/1 - 0s - loss: 0.0067 - 9ms/epoch - 9ms/step
Epoch 13/100
1/1 - 0s - loss: 0.0066 - 22ms/epoch - 22ms/step
Epoch 14/100
1/1 - 0s - loss: 0.0065 - 9ms/epoch - 9ms/step
Epoch 15/100
1/1 - 0s - loss: 0.0063 - 15ms/epoch - 15ms/step
Epoch 16/100
1/1 - 0s - loss: 0.0062 - 10ms/epoch - 10ms/step
Epoch 17/100
1/1 - 0s - loss:

# DL_2_1_trees.py

In [7]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/디지털오픈랩 딥러닝 교육/data/trees.csv')
df.head()

Unnamed: 0  Girth  Height  Volume
0           1    8.3      70    10.3
1           2    8.6      65    10.3
2           3    8.8      63    10.2
3           4   10.5      72    16.4
4           5   10.7      81    18.8

In [8]:
# 데이터 잘 불러오는 방법
df = pd.read_csv('/content/drive/MyDrive/디지털오픈랩 딥러닝 교육/data/trees.csv',
                            index_col=0)
df.head()

Girth  Height  Volume
1    8.3      70    10.3
2    8.6      65    10.3
3    8.8      63    10.2
4   10.5      72    16.4
5   10.7      81    18.8

In [9]:
print(df, end='\n\n')
print(df.values, end='\n\n')

    Girth  Height  Volume
1     8.3      70    10.3
2     8.6      65    10.3
3     8.8      63    10.2
4    10.5      72    16.4
5    10.7      81    18.8
6    10.8      83    19.7
7    11.0      66    15.6
8    11.0      75    18.2
9    11.1      80    22.6
10   11.2      75    19.9
11   11.3      79    24.2
12   11.4      76    21.0
13   11.4      76    21.4
14   11.7      69    21.3
15   12.0      75    19.1
16   12.9      74    22.2
17   12.9      85    33.8
18   13.3      86    27.4
19   13.7      71    25.7
20   13.8      64    24.9
21   14.0      78    34.5
22   14.2      80    31.7
23   14.5      74    36.3
24   16.0      72    38.3
25   16.3      77    42.6
26   17.3      81    55.4
27   17.5      82    55.7
28   17.9      80    58.3
29   18.0      80    51.5
30   18.0      80    51.0
31   20.6      87    77.0

[[ 8.3 70.  10.3]
 [ 8.6 65.  10.3]
 [ 8.8 63.  10.2]
 [10.5 72.  16.4]
 [10.7 81.  18.8]
 [10.8 83.  19.7]
 [11.  66.  15.6]
 [11.  75.  18.2]
 [11.1 80.  22.6]
 [11.

In [10]:
x = df.values[:, :-1]
# y = df.values[:, -1] # 1차원
y = df.values[:, -1:]   # 2차원
print(x.shape, y.shape)

(31, 2) (31, 1)


In [11]:
# quize
# trees.csv 파일을 읽고 학습하는 모델을 구축해서
# Birth 가 15이고 Height = 70 인 나무와, 
# Birth 가 20이고 Height = 80 인 나무의 Volume을 구하세요

In [12]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(shape=[2]))
model.add(tf.keras.layers.Dense(1))
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 1)                 3         
                                                                 
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.compile(optimizer=tf.keras.optimizers.SGD(0.00007),
              loss=tf.keras.losses.mse)

model.fit(x, y, epochs=1000, verbose=1)

Epoch 1/1000
1/1 [==============================] - 0s 227ms/step - loss: 20340.9805
Epoch 2/1000
1/1 [==============================] - 0s 7ms/step - loss: 802.4506
Epoch 3/1000
1/1 [==============================] - 0s 9ms/step - loss: 296.8133
Epoch 4/1000
1/1 [==============================] - 0s 6ms/step - loss: 283.2667
Epoch 5/1000
1/1 [==============================] - 0s 8ms/step - loss: 282.4439
Epoch 6/1000
1/1 [==============================] - 0s 8ms/step - loss: 281.9510
Epoch 7/1000
1/1 [==============================] - 0s 6ms/step - loss: 281.4676
Epoch 8/1000
1/1 [==============================] - 0s 6ms/step - loss: 280.9854
Epoch 9/1000
1/1 [==============================] - 0s 7ms/step - loss: 280.5040
Epoch 10/1000
1/1 [==============================] - 0s 8ms/step - loss: 280.0237
Epoch 11/1000
1/1 [==============================] - 0s 10ms/step - loss: 279.5442
Epoch 12/1000
1/1 [==============================] - 0s 7ms/step - loss: 279.0657
Epoch 13/1000
1/1 [=

In [14]:
print(model.predict([[15, 70],
                                 [20, 80]], verbose=0))

[[36.202736]
 [49.506207]]
